import json
import uuid
import pytest
from unittest.mock import AsyncMock
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.ai_employee import AIEmployee, AIEmployeeStatus
from app.models.company import Company
from app.models.conversation import Conversation
from app.models.document import Document, DocumentStatus
from app.models.document_chunk import DocumentChunk
from app.models.knowledge_base import KnowledgeBase, KnowledgeBaseStatus
from app.models.public_session import PublicChatSession
from app.services.public_runtime.security import hash_token
from app.services.voice.mock_providers import MockSTTProvider, MockTTSProvider
from app.services.voice.runtime import VoiceRuntimeManager


@pytest.mark.asyncio
async def test_voice_runtime_conversation_e2e_flow(db_session: AsyncSession):
    # Setup company, KB, document chunk, employee, and session
    company = Company(
        name="Voice Flow Co",
        slug=f"voiceflow-{uuid.uuid4().hex[:6]}",
    )
    db_session.add(company)
    await db_session.flush()

    kb = KnowledgeBase(
        company_id=company.id,
        name="Support Knowledge",
        status=KnowledgeBaseStatus.ACTIVE,
    )
    db_session.add(kb)
    await db_session.flush()

    doc_id = uuid.uuid4()
    doc = Document(
        id=doc_id,
        company_id=company.id,
        knowledge_base_id=kb.id,
        filename="Return_Policy.pdf",
        original_filename="Return Policy.pdf",
        file_type="pdf",
        mime_type="application/pdf",
        file_size=1024,
        storage_path=f"storage/{company.id}/{doc_id}/Return_Policy.pdf",
        status=DocumentStatus.PROCESSED,
    )
    db_session.add(doc)
    await db_session.flush()

    chunk = DocumentChunk(
        company_id=company.id,
        knowledge_base_id=kb.id,
        document_id=doc.id,
        chunk_index=0,
        content="Our standard return policy covers all retail items within 45 days of purchase.",
        token_count=16,
    )
    db_session.add(chunk)
    await db_session.flush()

    emp = AIEmployee(
        company_id=company.id,
        name="Voice Agent Priya",
        role="Customer Support",
        public_id=f"pub_voice_{uuid.uuid4().hex[:8]}",
        is_published=True,
        status=AIEmployeeStatus.ACTIVE,
        allowed_domains=["*"],
        voice_config={"voice_id": "mock_aria", "speed": 1.0},
    )
    emp.knowledge_bases.append(kb)
    db_session.add(emp)
    await db_session.flush()

    conv = Conversation(
        company_id=company.id,
        ai_employee_id=emp.id,
        title="Voice Call with Priya",
    )
    db_session.add(conv)
    await db_session.flush()

    import datetime
    raw_token = f"sess_pub_{uuid.uuid4().hex}"
    pub_session = PublicChatSession(
        company_id=company.id,
        ai_employee_id=emp.id,
        conversation_id=conv.id,
        token_hash=hash_token(raw_token),
        expires_at=datetime.datetime.now(datetime.timezone.utc) + datetime.timedelta(hours=24),
    )
    db_session.add(pub_session)
    await db_session.commit()

    # Track outgoing WebSocket frames
    sent_frames = []
    mock_ws = AsyncMock()
    mock_ws.client.host = "127.0.0.1"

    async def capture_send_text(text: str):
        sent_frames.append(json.loads(text))

    mock_ws.send_text.side_effect = capture_send_text

    stt = MockSTTProvider(canned_transcript="What is your return policy?")
    tts = MockTTSProvider()

    manager = VoiceRuntimeManager(
        websocket=mock_ws,
        session=db_session,
        stt_provider=stt,
        tts_provider=tts,
    )

    # 1. Authenticate
    await manager.authenticate_handshake(raw_token)
    assert manager.is_authenticated is True

    # 2. Process user audio utterance
    fake_audio = b"\x00" * 3200
    await manager.process_user_utterance(audio_data=fake_audio, audio_format="webm")

    # 3. Verify outgoing frame sequence: status -> transcript -> assistant_message -> audio_chunk -> status:idle
    frame_types = [f.get("type") for f in sent_frames]
    assert "transcribing" in [f.get("state") for f in sent_frames if f.get("type") == "status"]
    assert "transcript" in frame_types
    assert "thinking" in [f.get("state") for f in sent_frames if f.get("type") == "status"]
    assert "assistant_message" in frame_types
    assert "speaking" in [f.get("state") for f in sent_frames if f.get("type") == "status"]
    assert "audio_chunk" in frame_types

    # Verify transcript matches STT canned response
    transcript_frame = next(f for f in sent_frames if f.get("type") == "transcript")
    assert transcript_frame["text"] == "What is your return policy?"
    assert transcript_frame["is_final"] is True

    # Verify assistant message was generated by ConversationEngine
    asst_frame = next(f for f in sent_frames if f.get("type") == "assistant_message")
    assert len(asst_frame["text"]) > 0

    # Verify audio chunks were synthesized
    audio_frame = next(f for f in sent_frames if f.get("type") == "audio_chunk")
    assert "audio_base64" in audio_frame
    assert len(audio_frame["audio_base64"]) > 0

    # 4. Verify telemetry recording on close
    await manager.close_session()
    assert manager.voice_session_record.stt_requests == 1
    assert manager.voice_session_record.tts_requests >= 1
    assert manager.voice_session_record.total_latency_ms > 0
